workflows:
  android-debug:
    name: Android Debug APK
    environment:
      flutter: stable
    scripts:
      - name: Ensure Android scaffold
        script: |
          if [ ! -d "android" ] || [ ! -f "android/gradle/wrapper/gradle-wrapper.jar" ]; then
            flutter create --platforms=android .
          fi
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
